# ╒══════╗        ╒═══════╗
# │ ╓──┐ ║════════╗  ╓─┐  ║
# │ ╚══╛ ║──┐  ╓──╜  ║ │  ║  RustyTake-Off
# │ ╓─┐ ╓╜  │  ║  │  ║ │  ║  https://github.com/RustyTake-Off
# │ ║ │ ╚╗  │  ║  │  ╚═╛  ║
# └─╜ └──╜  └──╜  └───────╜
# Starship settings

# Starship: https://starship.rs
# Unicode characters: https://unicodes.jessetane.com

"$schema" = 'https://starship.rs/config-schema.json'

# Set prompt format
format = '$os$username@$hostname$directory$python$git_branch$git_status'
add_newline = false

# Change some of the colors
palette = 'custom'

[palettes.custom]
blue = '#4285f4'
orange = '#ffa700'
pink = '#ff71ce'
purple = '#8b00fd'

# Base prompt
[character]
success_symbol = ''
error_symbol = ''

[os]
format = '[$symbol]($style) '
style = 'white bold'
disabled = false

[os.symbols]
Windows = ''
Ubuntu = ''
Macos = '󰀵'

[username]
format = '[$user]($style)'
style_user = 'orange bold'
style_root = 'red bold'
show_always = true
disabled = false

[hostname]
format = '[$hostname]($style) '
style = 'yellow bold'
ssh_only = false
disabled = false

[directory]
format = 'at [$path]($style)[$read_only]($read_only_style) '
truncation_length = 1
truncation_symbol = '…/'
read_only = ''
read_only_style = 'red'
style = 'cyan bold'
disabled = false

# Git prompt
[git_branch]
format = '\[ [$branch]($style) '
truncation_symbol = '…/'
style = 'green bold'
disabled = false

[git_status]
format = '[$all_status$ahead_behind]($style)\] '
ahead = '⇡${count} '
behind = '⇣${count} '
conflicted = '⚠${count} '
deleted = 'X${count} '
diverged = '⇕⇡${ahead_count}⇣${behind_count} '
modified = 'M${count} '
renamed = 'R${count} '
staged = '±${count} '
stashed = '☖${count} '
untracked = '?${count} '
up_to_date = ''
style = 'green bold'
disabled = false

# Tools and languages prompts
[python]
format = '\[[$symbol(\($virtualenv\))]($style)\] '
symbol = 'PY'
style = 'green bold'
disabled = false

[nodejs]
format = '\[[$symbol]($style)\] '
symbol = 'NO'
style = 'orange bold'
disabled = true

[golang]
format = '\[[($symbol)]($style)\] '
symbol = 'GO'
style = 'cyan bold'
disabled = true

[rust]
format = '\[[$symbol]($style)\] '
symbol = 'RS'
style = 'red bold'
disabled = true

[kubernetes]
format = '\[[$symbol $context]($style)\] '
symbol = '☸'
style = 'blue bold'
disabled = true

[terraform]
format = '\[[$symbol]($style)\] '
symbol = 'TF'
style = 'purple bold'
disabled = true

[azure]
format = '\[[$symbol]($style)\] '
symbol = AZ'
style = 'blue bold'
disabled = true

[aws]
format = '\[[$symbol]($style)\] '
symbol = 'AWS'
style = 'red bold'
disabled = true

[gcloud]
format = '\[[$symbol]($style)\] '
symbol = 'GCP'
style = 'white bold'
disabled = true
