# Starship: https://starship.rs
# Unicode characters: https://unicodes.jessetane.com

"$schema" = 'https://starship.rs/config-schema.json'

# Set prompt format
format = '$time$os$username$hostname$directory$git_branch$git_status$python$conda$nodejs$golang$rust$docker_context$kubernetes$terraform$azure$aws$gcloud > '
add_newline = false

palette = 'custom'

[palettes.custom]
blue = '#4285f4'
orange = '#ffa700'
pink = '#ff71ce'
purple = '#8b00fd'

[character]
success_symbol = ''
error_symbol = ''

[time]
format = '[$time]($style) '
style = 'white bold'
time_format = '%R'
disabled = true

[os]
format = '[$symbol]($style) '
style = 'white bold'
disabled = true

[os.symbols]
Windows = ''
Ubuntu = ''
Macos = '󰀵'

[username]
format = '[$user]($style)'
style_user = 'orange bold'
style_root = 'red bold'
show_always = true
disabled = true

[hostname]
format = '@[$hostname]($style) '
style = 'yellow bold'
ssh_only = false
disabled = true

[directory]
format = '[$path]($style)[$read_only]($read_only_style) '
truncation_length = 1
truncation_symbol = '…/'
read_only = ''
read_only_style = 'red'
style = 'cyan bold'
disabled = false

[git_branch]
format = '\[[$branch/]($style)'
truncation_symbol = '…/'
style = 'green bold'
disabled = false

[git_status]
format = '[$all_status$ahead_behind]($style)\]'
style = 'green bold'
ahead = '⇡${count}'
behind = '⇣${count}'
conflicted = '⚠${count}'
deleted = 'X${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
modified = 'M${count}'
renamed = 'R${count}'
staged = '±${count}'
stashed = '☖${count}'
untracked = '?${count}'
up_to_date = ''
disabled = false

[python]
format = '\[[$symbol(\($virtualenv\))]($style)\]'
symbol = 'py'
style = 'green bold'
disabled = false

[conda]
format = '\[[$symbol(\($environment\))]($style)\]'
symbol = 'co'
style = 'green bold'
ignore_base = false
disabled = true

[nodejs]
format = '\[[$symbol]($style)\]'
symbol = 'njs'
style = 'orange bold'
disabled = true

[golang]
format = '\[[($symbol)]($style)\]'
symbol = 'go'
style = 'cyan bold'
disabled = true

[rust]
format = '\[[$symbol]($style)\]'
symbol = 'rs'
style = 'red bold'
disabled = true

[docker_context]
format = '\[[$symbol(\($context\))]($style)\]'
symbol = 'dc'
style = 'blue bold'
disabled = true

[kubernetes]
format = '\[[$symbol(\($context\))]($style)\]'
symbol = 'k8s'
style = 'blue bold'
disabled = true

[terraform]
format = '\[[$symbol]($style)\]'
symbol = 'tf'
style = 'purple bold'
disabled = true

[azure]
format = '\[[$symbol]($style)\]'
symbol = 'az'
style = 'blue bold'
disabled = true

[aws]
format = '\[[$symbol]($style)\]'
symbol = 'aws'
style = 'red bold'
disabled = true

[gcloud]
format = '\[[$symbol]($style)\]'
symbol = 'gcp'
style = 'white bold'
disabled = true
