name: 'Move wslfiles'
run-name: 'Move wslfiles'

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/*'
      - 'wslfiles/*'
      - '!wslfiles/README.md'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}

env:
  branchName: 'wslfiles'

jobs:
  move-files:
    runs-on: ubuntu-latest
    name: ${{ github.workflow }}
    steps:
      - name: 'Checkout repository'
        id: checkout-repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 'Move ${{ env.branchName }} files'
        id: move-branch-files
        uses: ./.github/actions/templates/moveFiles
        with:
          branchName: ${{ env.branchName }}
