name: 'Move files'
run-name: 'Move wslfiles'

on:
  push:
    branches:
      - main
    paths:
      - 'wslfiles/**'
      - '!wslfiles/README.md'

concurrency:
  group: ${{ github.workflow }}

permissions:
  contents: write

jobs:
  move-files:
    runs-on: ubuntu-latest
    name: 'Move wslfiles'

    steps:
      - name: 'Checkout repository'
        id: checkout-repo
        uses: actions/checkout@v4

      - name: 'Move files'
        id: move-files
        uses: ./.github/actions/templates/moveFiles
        with:
          CONFIG_FILE_PATH: 'wslfiles/to_move.yaml'
