name: "🐧 Move wslfiles"
run-name: "🐧 Move wslfiles"

on:
  push:
    branches:
      - main
    paths:
      - "shared/**"
      - "wslfiles/**"
      - "!**/README.md"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  move-files:
    runs-on: ubuntu-latest
    name: "Move files"
    environment: wslfiles

    steps:
      - name: "Checkout repository"
        id: checkout-repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Move files"
        id: move-files
        uses: ./.github/actions/templates/moveFiles
        with:
          CONFIG_FILE_PATH: "wslfiles/to_move.yaml"
