name: 'Move wslfiles'
run-name: 'Move wslfiles'

on:
  push:
    branches:
      - main
    paths:
      - '.github/**'
      - 'wslfiles/**'
      - '!wslfiles/README.md'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}

permissions:
  contents: write

env:
  targetBranchName: 'wslfiles'

jobs:
  move-files:
    runs-on: ubuntu-latest
    name: ${{ github.workflow }}
    steps:
      - name: 'Checkout repository'
        id: checkout-repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 'Move ${{ env.targetBranchName }} branch files'
        id: move-branch-files
        uses: ./.github/actions/templates/moveFiles
        continue-on-error: true
        with:
          targetBranchName: ${{ env.targetBranchName }}
