name: "Move wslfiles"
run-name: "🐧 Move wslfiles"

env:
  ENV_NAME: "wslfiles"

on:
  push:
    branches:
      - main
    paths:
      - "wslfiles/**"
      - "!wslfiles/README.md"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ env.ENV_NAME }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  move-files:
    runs-on: ubuntu-latest
    name: "Move ${{ env.ENV_NAME }}"
    environment: ${{ env.ENV_NAME }}

    steps:
      - name: "Checkout repository"
        id: checkout-repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Move files"
        id: move-files
        uses: ./.github/actions/templates/moveFiles
        with:
          CONFIG_FILE_PATH: "${{ env.ENV_NAME }}/to_move.yaml"
