name: 'Move files'

on:
  push:
    branches:
      - main
    paths:
      - 'wslfiles/*'
      - '!wslfiles/README.md'

env:
  branchName: 'wslfiles'

jobs:
  move-files-to-branch:
    runs-on: ubuntu-latest
    name: 'Move files to branch'
    steps:
      - name: 'Checkout repository'
        id: checkout-repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 'Move files'
        id: move-files
        uses: '../actions/templates/moveFiles/action.yaml'
        with:
          branchName: ${{ env.branchName }}


