name: 'Move files'

on:
  push:
    branches:
      - main
    paths:
      - 'wslfiles/*'
      - '!wslfiles/README.md'
  workflow_dispatch:

# env:
#   branchName: 'wslfiles'

jobs:
  move-files-to-branch:
    runs-on: ubuntu-latest
    name: 'Move files to branch'
    steps:
      - name: 'Checkout repository'
        id: checkout-repo
        uses: actions/checkout@v4

      - name: 'Move files'
        id: move-files
        uses: './.github/actions/templates/moveFiles/action.yaml'
        with:
          branchName: 'wslfiles'

      # - name: 'Move files'
      #   id: move-files
      #   shell: bash
      #   run: |
      #     pwd
      #     ls -al
