name: 'Move files'

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/*'
      - 'wslfiles/*'
      - '!wslfiles/README.md'
  workflow_dispatch:

jobs:
  move-files-to-branch:
    runs-on: ubuntu-latest
    name: 'Move files to branch'
    steps:
      - name: 'Checkout repository'
        id: checkout-repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 'Move files to'
        id: move-files1
        shell: bash
        run: |
          ls -al
          git branch
          echo "${{ toJson(github.event.commits[0].modified) }}"

      - name: 'Move files'
        id: move-files
        uses: ./.github/actions/templates/moveFiles
        with:
          branchName: 'wslfiles'