name: Update winfiles
run-name: '${{ github.workflow }} - #${{ github.run_number }} - ${{ github.event_name }}'

on:
    push:
        branches: [main]
        paths:
            - winfiles
            - '**/README.md'

jobs:
    commit-changes:
        name: Commit changes
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Setup git config
              run: |
                git config user.name 'github-actions[bot]'
                git config user.email 'github-actions[bot]@users.noreply.github.com'

            - name: Commit changes
              run: |
                git add winfiles -- ':!winfiles/README.md'
                git status
