name: 'Move files'
description: 'Move files to designated branch'

inputs:
  sourceBranchName:
    description: 'Source branch name for moving files'
    default: 'main'
    required: false
  targetBranchName:
    description: 'Target branch name for moving files'
    required: true

runs:
  using: 'composite'
  steps:
    - name: 'Move files to ${{ inputs.targetBranchName }}'
      id: move-files-to-branch
      shell: bash
      run: |
        # Switch branch
        git checkout -b ${{ inputs.targetBranchName }} --track origin/${{ inputs.targetBranchName }} &>/dev/null

        # Remove all files
        git rm -r . &>/dev/null
        git reset &>/dev/null

        # Checkout directory and move files
        git checkout ${{ inputs.sourceBranchName }} -- ${{ inputs.targetBranchName }} &>/dev/null

        cp -r "${{ inputs.targetBranchName }}"/* .
        find "${{ inputs.targetBranchName }}" -maxdepth 1 -name '.*[!.]*' -exec cp -r {} . \;

        # Clean up
        rm -rf ${{ inputs.targetBranchName }}
        rm README.md

        # Commit and push
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

        git add --all
        git commit -m "Update ${{ inputs.target_branch }}"

        git push origin ${{ inputs.target_branch }}
