name: 'Move files'
description: 'Move files to designated branch'

inputs:
  sourceBranchName:
    description: 'Source branch name for moving files'
    default: 'main'
    required: false
  targetBranchName:
    description: 'Target branch name for moving files'
    required: true
  otherSharedFiles:
    description: 'Shared files to move that are not in target branch (space separated)'
    default: ''
    required: false
  otherDirs:
    description: 'Other directories to move but not copy, that are not in target branch (space separated)'
    default: ''
    required: false
  userName:
    description: 'User name for config'
    default: 'github-actions[bot]'
    required: false
  userEmail:
    description: 'User email for config'
    default: '41898282+github-actions[bot]@users.noreply.github.com'
    required: false

runs:
  using: 'composite'
  steps:
    - name: 'Move files to ${{ inputs.targetBranchName }}'
      id: move-files-to-branch
      shell: bash
      run: |
        # Switch branch
        git checkout -b ${{ inputs.targetBranchName }} --track origin/${{ inputs.targetBranchName }} &>/dev/null

        # Remove all files
        git rm -r . &>/dev/null
        git reset &>/dev/null

        # Checkout directory and move files
        git checkout ${{ inputs.sourceBranchName }} -- ${{ inputs.targetBranchName }} ${{ inputs.otherDirs }} &>/dev/null

        [ -n "${{ inputs.otherSharedFiles }}" ] && \
        echo ${{ inputs.otherSharedFiles }}


        ls -al

        cp -r "${{ inputs.targetBranchName }}"/* .
        find "${{ inputs.targetBranchName }}" -maxdepth 1 -name '.*[!.]*' -exec cp -r {} . \;

        # Clean up
        rm -rf ${{ inputs.targetBranchName }}
        rm README.md

        # Commit and push
        git config --global user.name ${{ inputs.userName }}
        git config --global user.email ${{ inputs.userEmail }}

        git add --all
        git commit -m "Update ${{ inputs.target_branch }}"

        # git push origin ${{ inputs.target_branch }}
