name: 'Move files'
description: 'Move files to designated branch'

inputs:
  sourceBranchName:
    description: 'Source branch name for moving files'
    default: 'main'
    required: false
  targetBranchName:
    description: 'Target branch name for moving files'
    required: true

runs:
  using: 'composite'
  steps:
    - name: 'Move files to ${{ inputs.targetBranchName }}'
      id: move-files-to-branch
      shell: bash
      run: |
        # Switch branch
        git checkout -b ${{ inputs.targetBranchName }} --track origin/${{ inputs.targetBranchName }}

        # Remove all files
        git rm -r .
        git reset

        ls -al

        # Checkout directory and move files
        git checkout ${{ inputs.sourceBranchName }} -- ${{ inputs.targetBranchName }}

        find "${{ inputs.targetBranchName }}" -maxdepth 1 -name '.*[!.]*' -exec cp -r {} . \;
        # find "${{ inputs.targetBranchName }}" -maxdepth 1 -name '*' -type d -exec cp -r {} . \;

        # Clean up
        rm -rf ${{ inputs.targetBranchName }}
        # rm README.md

        echo '==='

        git status --short

        echo '==='

        ls -al
