name: 'Move files'
description: 'Move files to a designated branch'

inputs:
  branchName:
    description: 'Branch name'
    required: true

runs:
  using: 'composite'
  steps:
    - name: 'Move files to ${{ inputs.branchName }}'
      id: move-files
      shell: bash
      run: |
        ls -al
        git branch
