name: 'Move files'
description: 'Move files to designated branch'

inputs:
  branchName:
    description: 'Branch name to move files to'
    required: true

runs:
  using: 'composite'
  steps:
    - name: 'Move files to ${{ inputs.branchName }}'
      id: move-files-to-branch
      shell: bash
      run: |
        # Switch branch
        git checkout -b ${{ inputs.branchName }} --track origin/${{ inputs.branchName }}

        # Remove all files
        git rm -r .

        ls -al

        git status --short
        # git reset

        ls -al

        git checkout main -- ${{ inputs.branchName }}

        ls -al
