name: 'Move files'
description: 'Move files to designated branch'

inputs:
  sourceBranchName:
    description: 'Source branch name for moving files'
    default: 'main'
    required: false
  targetBranchName:
    description: 'Target branch name for moving files'
    required: true

runs:
  using: 'composite'
  steps:
    - name: 'Move files to ${{ inputs.targetBranchName }}'
      id: move-files-to-branch
      shell: bash
      run: |
        # Switch branch
        git checkout -b ${{ inputs.targetBranchName }} --track origin/${{ inputs.targetBranchName }}

        echo '---'

        # Remove all files
        git rm -r .

        echo '---'

        git reset

        echo '---'

        ls -al

        echo '---'

        # Checkout directory and move files
        git checkout ${{ inputs.sourceBranchName }} -- ${{ inputs.targetBranchName }}

        ls -al

        echo '---'

        cp ${{ inputs.targetBranchName }}/* . --recursive --force --verbose

        echo '---'

        ls -al

        # Clean up
        # rmdir ${{ inputs.targetBranchName }}
        # rm README.md
