name: 'Move files'
description: 'Move files to branch'

inputs:
  SOURCE_BRANCH_NAME:
    description: 'Source branch name e.g. main/master'
    default: 'main'
    required: false
  CONFIG_FILE_PATH:
    description: 'Path to the config file with files to move'
    required: true
  USER_NAME:
    description: 'User name for git config'
    default: 'github-actions[bot]'
    required: false
  USER_EMAIL:
    description: 'User email for git config'
    default: 'github-actions[bot]@users.noreply.github.com'
    required: false

runs:
  using: 'composite'
  steps:
    - name: 'Install yq'
      id: install-yq
      shell: bash
      run: |
        sudo curl -Lo /usr/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 \
        && sudo chmod +x /usr/bin/yq

    - name: 'Read YAML config'
      id: read-config
      shell: bash
      run: |
        TARGET_BRANCH_NAME=$(yq '.TARGET_BRANCH_NAME' "${{ inputs.CONFIG_FILE_PATH }}")
        OTHER_DIRS_FILES=$(yq '.OTHER_DIRS_FILES' "${{ inputs.CONFIG_FILE_PATH }}")
        echo "TARGET_BRANCH_NAME=${TARGET_BRANCH_NAME}" >> $GITHUB_ENV
        echo "OTHER_DIRS_FILES=${OTHER_DIRS_FILES}" >> $GITHUB_ENV

    - name: 'Move files to ${{ env.TARGET_BRANCH_NAME }}'
      id: move-files-to-branch
      shell: bash
      run: |
        .github/actions/templates/move_files.sh \
        "${{ inputs.SOURCE_BRANCH_NAME }}" \
        "${{ env.TARGET_BRANCH_NAME }}" \
        "${{ env.OTHER_DIRS_FILES }}" \
        "${{ inputs.USER_NAME }}" \
        "${{ inputs.USER_EMAIL }}"
